<$PLAN9/src/mkhdr

TARG=electron
LDFLAGS="-lrt -lncurses -lm"

OFILES=\
   agenda.$O\
   analysis.$O\
   ArchitectureDetection.$O\
   argacces.$O\
   binops.$O\
   bload.$O\
   bmathfun.$O\
   bsave.$O\
   classcom.$O\
   classexm.$O\
   classfun.$O\
   classinf.$O\
   classini.$O\
   classpsr.$O\
   clsltpsr.$O\
   commline.$O\
   conscomp.$O\
   constrct.$O\
   constrnt.$O\
   crstrtgy.$O\
   cstrcbin.$O\
   cstrccom.$O\
   cstrcpsr.$O\
   cstrnbin.$O\
   cstrnchk.$O\
   cstrncmp.$O\
   cstrnops.$O\
   cstrnpsr.$O\
   cstrnutl.$O\
   default.$O\
   defins.$O\
   developr.$O\
   dffctbin.$O\
   dffctbsc.$O\
   dffctcmp.$O\
   dffctdef.$O\
   dffctpsr.$O\
   dffnxbin.$O\
   dffnxcmp.$O\
   dffnxexe.$O\
   dffnxfun.$O\
   dffnxpsr.$O\
   dfinsbin.$O\
   dfinscmp.$O\
   drive.$O\
   emathfun.$O\
   engine.$O\
   envrnmnt.$O\
   evaluatn.$O\
   expressn.$O\
   exprnbin.$O\
   exprnops.$O\
   exprnpsr.$O\
   extnfunc.$O\
   factbin.$O\
   factbld.$O\
   factcmp.$O\
   factcom.$O\
   factfun.$O\
   factgen.$O\
   facthsh.$O\
   factlhs.$O\
   factmch.$O\
   factmngr.$O\
   factprt.$O\
   factqpsr.$O\
   factqury.$O\
   factrete.$O\
   factrhs.$O\
   filecom.$O\
   filertr.$O\
   generate.$O\
   genrcbin.$O\
   genrccmp.$O\
   genrccom.$O\
   genrcexe.$O\
   genrcfun.$O\
   genrcpsr.$O\
   globlbin.$O\
   globlbsc.$O\
   globlcmp.$O\
   globlcom.$O\
   globldef.$O\
   globlpsr.$O\
   HardwareDetection.$O\
   immthpsr.$O\
   incrrset.$O\
   inherpsr.$O\
   inscom.$O\
   insfile.$O\
   insfun.$O\
   insmngr.$O\
   insmoddp.$O\
   insmult.$O\
   inspsr.$O\
   insquery.$O\
   insqypsr.$O\
   iofun.$O\
   lgcldpnd.$O\
   main.$O\
   memalloc.$O\
   miscfun.$O\
   modulbin.$O\
   modulbsc.$O\
   modulcmp.$O\
   moduldef.$O\
   modulpsr.$O\
   modulutl.$O\
   msgcom.$O\
   msgfun.$O\
   msgpass.$O\
   msgpsr.$O\
   multifld.$O\
   multifun.$O\
   objbin.$O\
   objcmp.$O\
   objrtbin.$O\
   objrtbld.$O\
   objrtcmp.$O\
   objrtfnx.$O\
   objrtgen.$O\
   objrtmch.$O\
   OSDetection.$O\
   parsefun.$O\
   pattern.$O\
   Platform.$O\
   pprint.$O\
   prccode.$O\
   prcdrfun.$O\
   prcdrpsr.$O\
   prdctfun.$O\
   prntutil.$O\
   proflfun.$O\
   reorder.$O\
   reteutil.$O\
   retract.$O\
   router.$O\
   rulebin.$O\
   rulebld.$O\
   rulebsc.$O\
   rulecmp.$O\
   rulecom.$O\
   rulecstr.$O\
   ruledef.$O\
   ruledlt.$O\
   rulelhs.$O\
   rulepsr.$O\
   scanner.$O\
   sortfun.$O\
   strngfun.$O\
   strngrtr.$O\
   symblbin.$O\
   symblcmp.$O\
   symbol.$O\
   sysdep.$O\
   textpro.$O\
   tmpltbin.$O\
   tmpltbsc.$O\
   tmpltcmp.$O\
   tmpltdef.$O\
   tmpltfun.$O\
   tmpltlhs.$O\
   tmpltpsr.$O\
   tmpltrhs.$O\
   tmpltutl.$O\
   userdata.$O\
   userfunctions.$O\
   utility.$O\
   watch.$O\

HFILES=\
   agenda.h\
   analysis.h\
   ArchitectureDetection.h\
   argacces.h\
   binops.h\
   bload.h\
   bmathfun.h\
   bsave.h\
   classcom.h\
   classexm.h\
   classfun.h\
   classinf.h\
   classini.h\
   classpsr.h\
   clips.h\
   clsltpsr.h\
   cmptblty.h\
   commline.h\
   conscomp.h\
   constant.h\
   constrct.h\
   constrnt.h\
   crstrtgy.h\
   cstrcbin.h\
   cstrccmp.h\
   cstrccom.h\
   cstrcpsr.h\
   cstrnbin.h\
   cstrnchk.h\
   cstrncmp.h\
   cstrnops.h\
   cstrnpsr.h\
   cstrnutl.h\
   default.h\
   defins.h\
   developr.h\
   dffctbin.h\
   dffctbsc.h\
   dffctcmp.h\
   dffctdef.h\
   dffctpsr.h\
   dffnxbin.h\
   dffnxcmp.h\
   dffnxexe.h\
   dffnxfun.h\
   dffnxpsr.h\
   dfinsbin.h\
   dfinscmp.h\
   drive.h\
   emathfun.h\
   engine.h\
   envrnmnt.h\
   evaluatn.h\
   expressn.h\
   exprnbin.h\
   exprnops.h\
   exprnpsr.h\
   extnfunc.h\
   factbin.h\
   factbld.h\
   factcmp.h\
   factcom.h\
   factfun.h\
   factgen.h\
   facthsh.h\
   factlhs.h\
   factmch.h\
   factmngr.h\
   factprt.h\
   factqpsr.h\
   factqury.h\
   factrete.h\
   factrhs.h\
   filecom.h\
   filertr.h\
   generate.h\
   genrcbin.h\
   genrccmp.h\
   genrccom.h\
   genrcexe.h\
   genrcfun.h\
   genrcpsr.h\
   globlbin.h\
   globlbsc.h\
   globlcmp.h\
   globlcom.h\
   globldef.h\
   globlpsr.h\
   HardwareDetection.h\
   immthpsr.h\
   incrrset.h\
   inherpsr.h\
   inscom.h\
   insfile.h\
   insfun.h\
   insmngr.h\
   insmoddp.h\
   insmult.h\
   inspsr.h\
   insquery.h\
   insqypsr.h\
   iofun.h\
   lgcldpnd.h\
   match.h\
   memalloc.h\
   miscfun.h\
   modulbin.h\
   modulbsc.h\
   modulcmp.h\
   moduldef.h\
   modulpsr.h\
   modulutl.h\
   msgcom.h\
   msgfun.h\
   msgpass.h\
   msgpsr.h\
   multifld.h\
   multifun.h\
   network.h\
   objbin.h\
   objcmp.h\
   object.h\
   objrtbin.h\
   objrtbld.h\
   objrtcmp.h\
   objrtfnx.h\
   objrtgen.h\
   objrtmch.h\
   OSDetection.h\
   parsefun.h\
   pattern.h\
   Platform.h\
   pprint.h\
   prccode.h\
   prcdrfun.h\
   prcdrpsr.h\
   prdctfun.h\
   prntutil.h\
   proflfun.h\
   reorder.h\
   reteutil.h\
   retract.h\
   router.h\
   rulebin.h\
   rulebld.h\
   rulebsc.h\
   rulecmp.h\
   rulecom.h\
   rulecstr.h\
   ruledef.h\
   ruledlt.h\
   rulelhs.h\
   rulepsr.h\
   scanner.h\
   setup.h\
   sortfun.h\
   strngfun.h\
   strngrtr.h\
   symblbin.h\
   symblcmp.h\
   symbol.h\
   sysdep.h\
   textpro.h\
   tmpltbin.h\
   tmpltbsc.h\
   tmpltcmp.h\
   tmpltdef.h\
   tmpltfun.h\
   tmpltlhs.h\
   tmpltpsr.h\
   tmpltrhs.h\
   tmpltutl.h\
   userdata.h\
   usrsetup.h\
   utility.h\
   watch.h\

<$PLAN9/src/mkone
